// Hand-maintained — NOT regenerated by sync-from-host.mjs.
//
// Known LVIS marketplace signing public keys (ed25519, base64 raw 32B).
//
// The marketplace server signs every artifact with every configured private
// key (see server S4a dual-sign window). A downloaded signature envelope
// carries one entry per key. A client should treat the envelope as valid if
// AT LEAST ONE signature verifies against any public key listed here.
//
// Rotation policy:
//   - Adding a new key is additive — existing artifacts keep verifying via
//     their old signatures, and new artifacts will gain the new signature
//     once the server is redeployed with the corresponding private key.
//   - Removing a key (retirement / S4b) is a breaking change for clients
//     that only trust the removed key. Ship the removal in a new major SDK
//     version and coordinate with release telemetry before executing on
//     the server side.

/**
 * Known marketplace signing public keys, keyed by `key_id`.
 * Values are base64-encoded raw 32-byte ed25519 public keys.
 */
export const MARKETPLACE_PUBLIC_KEYS: Readonly<Record<string, string>> = Object.freeze({
  "dev-v1": "POA+RSsCG9akcaH6z410Jssk1FAy1ajA1Q0IWTRjZxg=",
  "prod-v1": "Qm3FUAMek2r5OkXCurgX6dNYSqiT1GRnjb5fWfuOoao=",
});

/**
 * Canonical key_id of the current production signing key. Clients that only
 * want to trust a single key for hardened deployments can rely on this.
 */
export const MARKETPLACE_PRIMARY_KEY_ID = "prod-v1" as const;
