// Hand-maintained — NOT regenerated by sync-from-host.mjs.
//
// LVIS marketplace signing public key (ed25519, base64 raw 32B).
//
// Single canonical signing key. The marketplace server signs every artifact
// with the corresponding private key; clients verify against the public key
// listed below. A future major SDK release will rotate this to a real
// production key once provisioned (currently a POC test key).

/**
 * Trusted marketplace signing public keys, keyed by `key_id`.
 * Values are base64-encoded raw 32-byte ed25519 public keys.
 */
export const MARKETPLACE_PUBLIC_KEYS: Readonly<Record<string, string>> = Object.freeze({
  "poc-v1": "Qm3FUAMek2r5OkXCurgX6dNYSqiT1GRnjb5fWfuOoao=",
});

/**
 * Returns the trusted public-key map for client-side signature verification.
 *
 * The single-key model intentionally drops the legacy dev-v1/dual-sign path —
 * pre-prod still uses POC keys, prod rotation is handled by shipping a new
 * SDK major (additive add, then remove the old key in a later major).
 */
export function getTrustedMarketplacePublicKeys(): Readonly<Record<string, string>> {
  return MARKETPLACE_PUBLIC_KEYS;
}

/**
 * Canonical key_id of the current marketplace signing key. The marketplace
 * server refuses to boot when `LVIS_ENV=production` is set with this key —
 * the prod rotation will replace this constant in a future major SDK.
 */
export const MARKETPLACE_PRIMARY_KEY_ID = "poc-v1" as const;
